version: '3.9'

services:
  file-sync-tool-app:
    container_name: file-sync-tool-app
    build: .
    environment:
      DATABASE_URL: "mysql://root:mysql_password@mysql_db:3306/file_sync_db"
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: file_sync_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}